### ISSUE TITLE
Help creating Payload Decoder

### ISSUE THREAD

**Issue by bigjdunham** [itec78/ttn2traccar#1]
Okay this is a great script, but now I need a little help creating the Payload Decoder. I don't know Java, so I'm don't even know where to start to create a Payload Decoder for my device that can be translated into OsmAnd for Traccar. Got any secrets, or know of a place to that would work for helping a dummy figure it out?

**Comment by itec78** [comment]
I used this firmware, and decoder was included

**Comment by itec78** [comment]
You should find a decoder for your device, probably you don't need to write it.
I used this firmware on my device, and the decoder was included.
https://github.com/kizniche/ttgo-tbeam-ttn-tracker

The decoder is used to decode the paylod into several values, and should be added to your device settings on TTN site (paylod formatters/uplink).
When payload is decoded (latitude, longitude, altitude) you can send it to a server running my script, that acts as a webservice and forwards data to traccar
